### ISSUE TITLE
Support latest version of CDK with `TypeScriptSource`

### ISSUE THREAD

**Issue by ehmicky** [mrgrain/cdk-esbuild#1364]
`TypeScriptSource` is incompatible with the latest version of `aws-s3-deployment`. 

More specifically, the `.bind()` method should return `{bucket, zipObjectKey}` instead of:

https://github.com/mrgrain/cdk-esbuild/blob/3ee7f93bb97c1fbaf689fe5277b8e6aded0389cc/src/code.ts#L105-L110

Also, `aws-s3-deployment` now passes the underlying Function `Role` as part of the second argument to the `.bind()` method. This can be used to automatically grant read access to the S3 Bucket. An example can be found [here](https://github.com/aws/aws-cdk/blob/c159e77ab34701fc6780b9501f1692fbf2366b04/packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts#L120).

**Comment by mrgrain** [comment]
Hi @ehmicky  Thanks for reporting! Could it be that you tried to use `TypeScriptCode` where `TypeScriptSource` is expected? The code you've linked seems to indicate that.  🤔 

This is the respective code in `TypeScriptSource` and it looks all correct, including the `handlerRole`:
https://github.com/mrgrain/cdk-esbuild/blob/3ee7f93bb97c1fbaf689fe5277b8e6aded0389cc/src/source.ts#L90-L95

Also the [latest version integration tests](https://github.com/mrgrain/cdk-esbuild/actions/runs/10412340677/job/28838014771) haven't picked up on it, nor has aws-s3-deployment [changed](https://github.com/aws/aws-cdk/commits/main/packages/aws-cdk-lib/aws-s3-deployment/lib/source.ts) significantly recently.

**Comment by ehmicky** [comment]
This is absolutely correct!
Sorry about the noise! Great project. :pray:
