### ISSUE TITLE
Use node require resolutions

### ISSUE THREAD

**Issue by moltar** [mrgrain/cdk-esbuild#185]
**Is your feature request related to a problem? Please describe.**

Right now, a relative path to the `cwd` needs to be specified.

```ts
new TypeScriptCode('src/edge.ts')
```

I usually use the Node's resolution via require when specifying Lambda entries.

```ts
new lambda.NodejsFunction(this, 'MyFunction', {
  entry: require.resolve('./edge'), // <-- will be resolved by node relative to the current file
});
```

**Describe the solution you'd like**

Ability to resolve using Node's require, like so:

```ts
new TypeScriptCode('./edge')
```

I think maybe can try to resolve the files via `require.resolve` inside try/catch to maintain backward compat.

**Describe alternatives you've considered**

Using file system paths.

**Additional context**

N/A

**Comment by mrgrain** [comment]
Hey @moltar  thanks for submitting the issue!

_Rephrasing your report for my understanding:_
Is this basically about being able to use an absolute path as entrypoint as long as the path is still within the esbuild working dir (which defaults to cwd)?

**Comment by moltar** [comment]
> Is this basically about being able to use an absolute path as entrypoint, as long as the entrypoint is still within the esbuild's working dir (which defaults to cwd)?

Me parsing that:

![image](https://user-images.githubusercontent.com/491247/178497956-530348f3-4baa-461d-8b42-636b03af8af6.png)

Slow today 😂 

---

I _think_ it is about being able to use the _relative_ path in the CDK code, which is relative to the file _with_ CDK code.

Bonus: also, can drop the extension.

Here's a real life example:

```ts
    const authz = new aws_cloudfront.experimental.EdgeFunction(this, 'Authz', {
      code: new TypeScriptCode(path.relative(process.cwd(), require.resolve('./edge'))),
      handler: 'index.handler',
      runtime: Runtime.NODEJS_16_X,
    });
```

I wish I could have written it simply as:

```ts
    const authz = new aws_cloudfront.experimental.EdgeFunction(this, 'Authz', {
      code: new TypeScriptCode('./edge'),
      handler: 'index.handler',
      runtime: Runtime.NODEJS_16_X,
    });
```

And under the hood, it would "resolve" and figure out the location of the file.

---

But, I also now realize it is an impossibility.

Because `require.resolve` would be relevant to _your_ library's file.

**Comment by mrgrain** [comment]
Haha apologies. I guess I was feeling similar when I was trying to understand your original query. 🙈 

> which is relative to the file with CDK code.
> But, I also now realize it is an impossibility.

Aside from the impossibility, I'm not sure I'm convinced it is the more common use case. And unfortunately I have to make a decision for a default.

My arguments for keep defaulting to `cwd`:
- It's would be breaking change
- While there are many different ways of structuring a CDK app, I found it easier (and also it seems quite common) to keep infrastructure code and lambda code somewhat separate. Think an `infrastructure` and a `src` folder.
- Some esbuild features like `external` feel more natural on the top level. E.g. `--external:./node_modules/*` vs `--external:../../node_modules/*`

Saying that, I think the following should be supported:
```ts
    const authz = new aws_cloudfront.experimental.EdgeFunction(this, 'Authz', {
      code: new TypeScriptCode(require.resolve('./edge')),
      handler: 'index.handler',
      runtime: Runtime.NODEJS_16_X,
    });
```
Which at the moment doesn't work due to enforcement of relative paths. And `require.resolve` returns an absolute path.

**Comment by moltar** [comment]
> Saying that, I think the following should be supported:

That would be ok.

I just don't like relying on `cwd` ever. As it _always_ backfires eventually.

This is especially problematic when putting this into a reusable construct.

**Comment by mrgrain** [comment]
I do have a recommendation for reusable constructs that are consumed as libraries:
https://github.com/mrgrain/cdk-esbuild#library-authors

From that perspective I can see the argument for defaulting to the file path. With the current approach I'm not sure if you can get around setting `absWorkingDir`.

**Comment by mrgrain** [comment]
@moltar I've got a PR ready for this. Reviews are welcome!

https://github.com/mrgrain/cdk-esbuild/pull/186
