### ISSUE TITLE
esbuild binary path is not correctly detected in 3.6.0 and 3.7.0 when using Yarn 2 Plug&Play

### ISSUE THREAD

**Issue by matthias-pichler-warrify** [mrgrain/cdk-esbuild#189]
**Describe the bug**

We have a cdk application that uses Yarn 2 Plug and Play. We use this package to leverage the [esbuild-plugin-pnp](https://www.npmjs.com/package/@yarnpkg/esbuild-plugin-pnp) as described [in your examples](https://github.com/mrgrain/cdk-esbuild/tree/31ef1964a0fc335aa374a3f6871e6b4a734b67ee/examples/esbuild-with-plugins). 

When we upgrade to 3.6.0 or 3.7.0 `cdk synth` fails with

```
Bundling asset end-user-iam-dev-feature-ceg-m-ikccks/UserPool/CognitoLambdas/PostConfirmation/TypeScriptCode/Stage...
Error: The service was stopped: spawn undefined ENOENT
    at /builds/warrify/services/end-user-iam/.yarn/unplugged/esbuild-npm-0.14.49-8ea32c7f59/node_modules/esbuild/lib/main.js:1337:25
    at /builds/warrify/services/end-user-iam/.yarn/unplugged/esbuild-npm-0.14.49-8ea32c7f59/node_modules/esbuild/lib/main.js:666:9
    at ChildProcess.afterClose (/builds/warrify/services/end-user-iam/.yarn/unplugged/esbuild-npm-0.14.49-8ea32c7f59/node_modules/esbuild/lib/main.js:644:7)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^
Error: The service was stopped: spawn undefined ENOENT
    at /builds/warrify/services/end-user-iam/.yarn/unplugged/esbuild-npm-0.14.49-8ea32c7f59/node_modules/esbuild/lib/main.js:13[37](https://gitlab.com/warrify/services/end-user-iam/-/jobs/2709204974#L37):25
    at /builds/warrify/services/end-user-iam/.yarn/unplugged/esbuild-npm-0.14.49-8ea32c7f59/node_modules/esbuild/lib/main.js:666:9
    at ChildProcess.afterClose (/builds/warrify/services/end-user-iam/.yarn/unplugged/esbuild-npm-0.14.49-8ea32c7f59/node_modules/esbuild/lib/main.js:644:7)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
/builds/warrify/services/end-user-iam/.yarn/unplugged/aws-cdk-lib-virtual-[47](https://gitlab.com/warrify/services/end-user-iam/-/jobs/2709204974#L47)bf6f84bd/node_modules/aws-cdk-lib/core/lib/asset-staging.js:2
```

The interesting part being `spawn undefined ENOENT`

When we explicitly set `ESBUILD_BINARY_PATH=/workspace/npm-packages/.yarn/unplugged/esbuild-npm-0.14.49-8ea32c7f59/node_modules/esbuild/lib/pnpapi-esbuild-linux-64-esbuild` or `ESBUILD_BINARY_PATH=/workspace/npm-packages/.yarn/unplugged/esbuild-linux-64-npm-0.14.49-96241737d6/node_modules/esbuild-linux-64/bin/esbuild` then synth succeeds. 

To make things even weirder: The first lambda function build succeeds but if you have more than 1 Lambda Function then it starts failing (the stack trace shows that the error comes from [esbuild in a function named `buildOrServeContinue`](https://github.com/evanw/esbuild/blob/f730c03dc7be43c3c908fbd6e106120a99ebb4a0/lib/shared/common.ts#L1122)).

**To Reproduce**

1. Create a repo using yarn 2 plug&play
1. Create a stack with 2 lambda functions
1. run `cdk synth`

**Expected behavior**

The automatic inference of the binary path should continue to work as it did in 3.5.0 

**Versions:**
 - CDK: 2.31.1
 - Node.js: 16.16.0

**Additional context**

**Comment by matthias-pichler-warrify** [comment]
I think the bug is [here](https://github.com/mrgrain/cdk-esbuild/blob/main/src/bundler.ts#L198). In the detection if esbuild is running it sets `ESBUILD_BINARY_PATH` itself. 

so the flow is:
1. `ESBUILD_BINARY_PATH === undefined`
2. [this line](https://github.com/mrgrain/cdk-esbuild/blob/31ef1964a0fc335aa374a3f6871e6b4a734b67ee/src/bundler.ts#L181) stores it in `originalEsbuildBinaryPath`
3. esbuild is executed the first time (and succeeds) and thereby sets `ESBUILD_BINARY_PATH`
4. [this line](https://github.com/mrgrain/cdk-esbuild/blob/main/src/bundler.ts#L198) is run and overrides the setting again with `undefined`

**Comment by mrgrain** [comment]
Oh good catch. And thanks for the fix! 🕺

We probably need to get some yarn tests in there eventually 😅
